name: Java CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: eskatos/gradle-command-action@v1
        name: Generate license report
        with:
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: licenseReportZip
      - uses: actions/upload-artifact@v4
        with:
          name: report
          path: build/license-report.zip
