name: Java CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Generate license report
        run: ./gradlew licenseReportZip
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: build/license-report.zip
